version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
      - backend_static_volume:/backend/static
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend_network
      - nginx_network
    depends_on:
      - backend_postgresql
  backend_postgresql:
    image: postgres:latest
    container_name: backend_postgresql
    volumes:
      - backend_postgresql:/var/lib/postgresql/data
    
    restart: always
    env_file: .env
    ports:
    - "5432:5432"
    networks:
      - backend_network

volumes:
  backend_postgresql:
    external: true
  backend_static_volume:
    external: true
networks:
  backend_network:
    external: true
  nginx_network:
    external: true